language: cpp
dist: trusty
sudo: false
group: beta

addons:
  apt:
    sources:
      - 'ubuntu-toolchain-r-test'
      - 'boost-latest'
    packages:
      - 'g++-multilib'
      - 'libboost-serialization-dev'
#      - 'libboost-test-dev'

compiler:
  - gcc

matrix:
  include:
    - os: linux
      compiler: clang
      env: CMAKE_OPTIONS="-DSKIP_PORTABILITY_TEST=ON"

    # TODO: Add an entry for valgrind
    #  after_script: make valgrind

    - os: osx
      osx_image: xcode8
      compiler: clang

script:
  - mkdir build && cd build
  - cmake ${CMAKE_OPTIONS} .. && make -j4
  - ctest . --output-on-failure

branches:
  only:
    - develop
