# set(VLFEAT_INCLUDE_DIR ${PROJECT_SOURCE_DIR}/ext/vlfeat)
set(VLFEAT_INCLUDE_DIR ${PROJECT_SOURCE_DIR}/ext)
include_directories(${VLFEAT_INCLUDE_DIR})

# set(VLFEAT_LIBRARIES ${PROJECT_SOURCE_DIR}/lib/libvlfeat.a)